/* Copyright (c) 2014 Brivium (http://brivium.com)
 * Author: Brivium
 * Addon: ModernStatistic
 * Version: 2.4.1
 * Released under the Brivium License Agreement: http://brivium.com/pages/terms-of-use/
 */

/** @param {jQuery} $ jQuery Object */
!function(b,e,m,n){XenForo.BRMSContainer=function(a){this.__construct(a)};XenForo.BRMSContainer.prototype={__construct:function(a){this.$container=a;var c=a.attr("data-previewType"),g=parseInt(a.attr("data-allowCusItemLimit")),f=parseInt(a.attr("data-allowCusLayout")),d=a.attr("data-useLimit"),h=a.attr("data-entryLimit"),k=a.attr("data-navPosition"),l=parseInt(a.attr("data-updateInterval"));$modernStatisticId=parseInt(a.attr("data-modernStatisticId"));this.$containerClass="BRMSContainer ";a.hasClass("BRMSContainerDark")&&
(this.$containerClass="BRMSContainer BRMSContainerDark ");this.$previewType=c;this.$allowCusItemLimit=g;this.$allowCusLayout=f;this.$entryLimit=h;this.$navPosition=k;this.$updateIntervalTime=l;this.$modernStatisticId=$modernStatisticId;this.$hardReload=!1;$this=this;$customLayout=b.cookie("brmsLayoutChange"+$modernStatisticId);f&&$customLayout&&(a.hasClass($customLayout)||a.attr("class",$this.$containerClass+$customLayout));console.log(d);d&&0<parseInt(d)?($this.$entryLimit=d,a.attr("data-entryLimit",
d)):this.$allowCusItemLimit&&b.cookie("brmsNumberEntry"+$modernStatisticId)&&($this.$entryLimit=b.cookie("brmsNumberEntry"+$modernStatisticId),a.attr("data-entryLimit",b.cookie("brmsNumberEntry"+$modernStatisticId)));$numberNav=a.find("ul.brmsTabNav > li").length-2;a.find("ul.brmsTabNav > li:first").addClass("first");a.find("ul.brmsTabNav > li:eq("+$numberNav+")").addClass("last");a.find("ul.brmsTabNav > li > a, .brmsTabNavHidden  ul.brmsDropdownMenu  > li > a").click(b.context(this,"navTabTriggerHandle"));
this.showTab(a.find(".brmsTabContent:first").data("content"));this.updateInterval();a.find(".brmsNumberEntry").click(b.context(this,"numberEntryChangeHandle"));a.find(".brmsLayoutChange").click(b.context(this,"layoutChangeHandle"));a.find(".brmsRefresh").click(b.context(this,"refreshHandle"));this.responsiveInit();b(e).resize(b.context(this,"responsiveInit"));a.find(".brmsDropdownToggle").hover(function(c){$drMenu=b(this).find("ul.brmsDropdownMenu");$drMenu.show();$drMenu.offset().left+$drMenu.width()>
a.width()?$drMenu.addClass("edge"):$drMenu.removeClass("edge");"none"!=$drMenu.css("display")&&0>=$drMenu.offset().left&&$drMenu.css({left:0})},function(c){b(this).find("ul.brmsDropdownMenu").hide();$drMenu.offset().left+$drMenu.width()>a.width()?$drMenu.addClass("edge"):$drMenu.removeClass("edge");"none"!=$drMenu.css("display")&&0>=$drMenu.offset().left&&$drMenu.css({left:0})});a.find(".brmsDropdownToggle").click(function(a){b(this).find("ul.brmsDropdownMenu").toggle()})},navTabTriggerHandle:function(a){$container=
this.$container;$handleBtn=b(a.target);console.log($handleBtn);$handleBtn.attr("data-content")||($handleBtn=$handleBtn.closest("a"));$liParent=$handleBtn.closest("li");$handleBtn.closest("li");$liParent&&!$liParent.hasClass("current")&&($container.find("ul.brmsTabNav > li , .brmsTabNavHidden  ul.brmsDropdownMenu  > li").removeClass("current"),$handleBtn.closest("li").addClass("current"),$contentClass=$handleBtn.attr("data-content"),$container.find("."+$contentClass).find(".brmsIcoLoader").length&&
this.getStatistics($handleBtn.attr("data-tabid"),0),$container.find(".brmsTabContent").hide().removeClass("current"),$container.find("."+$contentClass).fadeIn(100).addClass("current"),this.responsiveInit());a.preventDefault()},numberEntryChangeHandle:function(a){$container=this.$container;$handleBtn=b(a.target);if($limit=$handleBtn.attr("data-limit"))this.$entryLimit=$limit,$container.attr("data-entryLimit",$limit),b.cookie("brmsNumberEntry"+this.$modernStatisticId,$limit),this.resetInterval(),this.$hardReload=
1,this.runInterval(),this.$hardReload=!1;a.preventDefault()},layoutChangeHandle:function(a){$container=this.$container;$handleBtn=b(a.target);$layout=$handleBtn.attr("data-layout");$this=this;$layout&&($container.hasClass($layout)||$container.attr("class",$this.$containerClass+$layout),b.cookie("brmsLayoutChange"+this.$modernStatisticId,$layout),$this.responsiveInit());a.preventDefault()},refreshHandle:function(a){$handleBtn=b(a.target);$handleBtn.hasClass("disable")||(this.resetInterval(),this.$hardReload=
1,$handleBtn.addClass("disable"),this.runInterval(),this.$hardReload=!1);a.preventDefault()},getStatistics:function(a,c){$container=this.$container;$modernStatisticId=this.$modernStatisticId;$this=this;c||(c=$this.$entryLimit);($loadUrl=($container.attr("data-loadUrl"),$container.attr("data-loadUrl")))||($loadUrl="index.php?brms-statistic/statistics.json");XenForo.ajax($loadUrl,{tab_id:a,modern_statistic_id:$modernStatisticId,hard_reload:$this.$hardReload,limit:c},b.context(this,"showResult"),{cache:!1})},
showResult:function(a){$container=this.$container;$this=this;if(!1!==XenForo.hasResponseError(a))return!0;$currentContent=$container.find(".brmsTabContent_"+a.tabId);a.tabContentHtml?$currentContent.html(a.tabContentHtml):$currentContent.html("");console.log("Mordern Statistic Loaded");a.limit&&($container.attr("data-entryLimit",a.limit),$this.$entryLimit=a.limit);$container.xfActivate();$container.find(".brmsRefresh").removeClass("disable");$this.responsiveInit()},showTab:function(a){$container=
this.$container;a?($container.find("ul.brmsTabNav > li > a[data-content='"+a+"']").trigger("click"),$tabId=a.replace("brmsTabContent_","")):($container.find("ul.brmsTabNav > li.current a").trigger("click"),$tabId=$container.find("ul.brmsTabNav > li.current a").attr("data-content").replace("brmsTabContent_",""))},runInterval:function(){$container=this.$container;$this=this;$this.getStatistics($container.find("li.brmlShow.current a").data("tabid"),$this.$entryLimit)},updateInterval:function(){if(!this.$brmsActive&&
($brmsInterval=this.$updateIntervalTime,$this=this,0<$brmsInterval))return this.$brmsActive=e.setInterval(function(){console.log("Mordern Statistic Update "+$brmsInterval+"s");$this.getStatistics($container.find("ul.brmsTabNav > li.current a").data("tabid"),$this.$entryLimit)},1E3*$brmsInterval)},clearInterval:function(){e.clearInterval(this.$brmsActive);this.$brmsActive=!1;return this.$updateIntervalTime=0},resetInterval:function(){this.clearInterval();this.updateInterval()},responsiveInit:function(){$container=
this.$container;$brmsLayoutList=$container.find(".brmsLayoutList");$container.hasClass("brmsTopTabs")?($tabNavWidth=0,$calWidth=$container.find(".brmsStatisticHeader").width()-$container.find(".brmsConfigList").width()-75,$showHiddenMenu=!1,$container.find(".brmsTabNav > li.brmlShow").each(function(){$same=$container.find(".brmsTabNavHidden li:eq("+b(this).index()+")");$tabNavWidth+b(this).width()<=$calWidth?($tabNavWidth+=b(this).width(),b(this).css({display:"block"}),$same.hasClass("current")&&
(b(this).addClass("current"),$same.removeClass("current")),$same.css({display:"none"})):($showHiddenMenu=!0,b(this).css({display:"none"}),b(this).hasClass("current")&&(b(this).removeClass("current"),$same.addClass("current")),$same.css({display:"block"}))}),$brmsTabNavHiddenMenu=$container.find(".brmsTabNavHiddenMenu"),$showHiddenMenu?$brmsTabNavHiddenMenu.show():$brmsTabNavHiddenMenu.hide(),480<$container.width()?(b.cookie("brmsLayoutChange"+this.$modernStatisticId)&&!$container.hasClass(b.cookie("brmsLayoutChange"+
this.$modernStatisticId))&&$container.attr("class",this.$containerClass+b.cookie("brmsLayoutChange"+this.$modernStatisticId)),$brmsLayoutList.css({display:"inline-block"})):$brmsLayoutList.css({display:"none"})):480>=$container.width()&&($container.attr("class",this.$containerClass+" brmsTopTabs"),$brmsLayoutList.css({display:"none"}));$itemStast=$container.find(".brmsTabContent.current ol li.itemStast");550>$container.find(".brmsTabContent.current").width()?$itemStast.hasClass("itemUser")?($itemStast.find(".itemDetail.itemSubDetail").hide(),
$itemStast.find(".itemTitle").css({"max-width":"75%"}),350>$container.find(".brmsTabContent.current").width()?($itemStast.find(".itemDetail.itemDetailMain span").hide(),$itemStast.find(".itemDetail.itemDetailMain").css({width:"50px"}),$itemStast.find(".itemDetail.itemDetailMain.itemDate").css({width:"90px"}),$itemStast.find(".itemTitle").css({"max-width":"85%"})):($itemStast.find(".itemDetail.itemDetailMain span, .itemDetail.itemDetailMain strong").show(),$itemStast.find(".itemDetail.itemDetailMain").css({width:"200px"}),
$itemStast.find(".itemTitle").css({"max-width":"75%"}))):($itemStast.find(".itemDetail").hide(),$itemStast.find(".itemTitle").css({"max-width":"90%"}),350>$container.find(".brmsTabContent.current").width()?$itemStast.find(".prefix").hide():$itemStast.find(".prefix").show()):($itemStast.find(".prefix").show(),$itemStast.find(".itemDetail").show(),$itemStast.find(".itemTitle").css({width:"auto"}),$itemStast.find(".itemDetail.itemDetailMain span").show(),$itemStast.find(".itemDetail.itemDetailMain").css({width:"150px"}),
$itemStast.find(".itemDetail.itemDetailMain.itemDate").css({width:"200px"}));$stastWidth=parseInt(.33*$itemStast.width());$itemTitleWidth=$itemStast.find(".itemTitle").width();$itemStast.find(".itemSubDetail").each(function(a){"none"==b(this).css("display")?$itemTitleWidth-150>$stastWidth&&$itemStast.find(".itemSubDetail:eq("+a+")").show():$itemTitleWidth<$stastWidth&&$itemStast.find(".itemSubDetail:eq("+a+")").hide()})},getText:function(a,b){return BRMSLANG.xf[a]||b}};XenForo.BRMSToolTip=function(a){this.__construct(a)};
XenForo.BRMSToolTip.prototype={__construct:function(a){this.$item=a.find(".itemTitle > a");a.hover(b.context(this,"showTooltip"),b.context(this,"hideTooltip"));this.$listItem=a},showTooltip:function(){this.$toolTip=b(this.toolTips(this.$item));b(this.toolTips(this.$item)).show().insertBefore(this.$item)},hideTooltip:function(){this.$listItem.find(".brmsToolTips").remove()},toolTips:function(a){if("resource"==a.attr("data-kind")&&a.attr("data-box"))return'<div class="xenTooltip brmsToolTips"><div>['+
this.getText("category")+"] : <b>"+a.attr("data-box")+"</b></div><div>["+this.getText("download")+"] : <b>"+a.attr("data-download")+"</b> - ["+this.getText("update")+"] : <b>"+a.attr("data-update")+"</b> - ["+this.getText("review")+"] : <b>"+a.attr("data-review")+"</b> - ["+this.getText("all_time_rating")+"] : <b>"+a.attr("data-vote")+'</b></div><span class="arrow"></span></div>';if(a.attr("data-box"))return'<div class="xenTooltip brmsToolTips"><div>['+this.getText("forum")+"] : <b>"+a.attr("data-box")+
"</b></div><div>["+this.getText("views")+"] : <b>"+a.attr("data-view")+"</b> - ["+this.getText("replies")+"] : <b>"+a.attr("data-rep")+"</b> - ["+this.getText("likes")+"] : <b>"+a.attr("data-like")+'</b></div><span class="arrow"></span></div>'},getText:function(a,b){return BRMSLANG.xf[a]||b}};XenForo.register(".BRMSContainer","XenForo.BRMSContainer");XenForo.register(".BRMSToolTip","XenForo.BRMSToolTip")}(jQuery,this,document);